--liquibase formatted sql

-- changeset yourname:001_create_tables

create table users (
       id bigint primary key generated by default as identity,
       email varchar(255) not null,
       login varchar(255) not null,
       password varchar(512) not null,
       role varchar(20) not null
);

create table customers (
       id bigint primary key generated by default as identity,
       name varchar(255) not null,
       city varchar(255) not null,
       street varchar(255) not null,
       zipcode varchar(20) not null,
       foreign key (id) references users(id)
);

create table orders (
        id bigint primary key generated by default as identity,
        date timestamp not null,
        status varchar(50) not null,
        customer_id bigint not null,
        foreign key (customer_id) references customers(id)
);

create table items (
       id bigint primary key generated by default as identity,
       shipping_weight decimal not null,
       description text not null,
       measurement_name varchar(255) not null,
       measurement_symbol varchar(50) not null
);

create table order_details (
       id bigint primary key generated by default as identity,
       quantity_value int not null,
       quantity_unit varchar(50),
       quantity_description varchar(255),
       tax_status varchar(50) not null,
       order_id bigint not null,
       item_id bigint not null,
       foreign key (order_id) references orders(id),
       foreign key (item_id) references items(id)
);

create table payments (
      id bigint primary key generated by default as identity,
      amount float not null,
      payment_type varchar(50) not null,
      cash_tendered float,
      name varchar(255),
      bank_id varchar(50),
      credit_number varchar(50),
      credit_type varchar(50),
      exp_date timestamp,
      order_id bigint not null,
      foreign key (order_id) references orders(id)
);


create table banned_tokens (
    token text primary key
);

create table sessions (
      id bigint primary key generated by default as identity,
      user_id bigint not null,
      token varchar(255) not null unique,
      expiration_time timestamp not null,
      foreign key (user_id) references users(id)
);

-- changeset yourname:002_create_sub

alter table users
    add column if not exists sub varchar(512);

-- rollback drop table customers, orders, items, order_details, payments;