--liquibase formatted sql

-- changeset yourname:001_create_tables

-- Создание таблицы customers
CREATE TABLE customers (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           name VARCHAR(255) NOT NULL,
                           city VARCHAR(255),
                           street VARCHAR(255),
                           zipcode VARCHAR(20)
);

-- Создание таблицы items
CREATE TABLE items (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       description VARCHAR(255),
                       shipping_weight_value DECIMAL(19,2),
                       shipping_weight_name VARCHAR(50),
                       shipping_weight_symbol VARCHAR(10)
);

-- Создание таблицы orders
CREATE TABLE orders (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        date TIMESTAMP NOT NULL,
                        status VARCHAR(50) NOT NULL,
                        customer_id BIGINT NOT NULL,
                        CONSTRAINT fk_order_customer FOREIGN KEY (customer_id) REFERENCES customers(id)
);

-- Создание таблицы order_details
CREATE TABLE order_details (
                               order_id BIGINT NOT NULL,
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               quantity_value INT,
                               quantity_name VARCHAR(50),
                               quantity_symbol VARCHAR(10),
                               tax_status VARCHAR(50),
                               item_id BIGINT NOT NULL,
                               CONSTRAINT fk_orderdetails_order FOREIGN KEY (order_id) REFERENCES orders(id),
                               CONSTRAINT fk_orderdetails_item FOREIGN KEY (item_id) REFERENCES items(id)
);

-- Создание таблицы payments
CREATE TABLE payments (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          amount FLOAT NOT NULL,
                          order_id BIGINT NOT NULL UNIQUE,
                          payment_type VARCHAR(20) NOT NULL,
                          payment_status VARCHAR(20) NOT NULL,
                          CONSTRAINT fk_payment_order FOREIGN KEY (order_id) REFERENCES orders(id)
);

-- Создание таблицы cash_payments
CREATE TABLE cash_payments (
                               id BIGINT PRIMARY KEY,
                               cash_tendered FLOAT NOT NULL,
                               CONSTRAINT fk_cash_payment FOREIGN KEY (id) REFERENCES payments(id)
);

-- Создание таблицы check_payments
CREATE TABLE check_payments (
                                id BIGINT PRIMARY KEY,
                                name VARCHAR(255) NOT NULL,
                                bank_id VARCHAR(50) NOT NULL,
                                CONSTRAINT fk_check_payment FOREIGN KEY (id) REFERENCES payments(id)
);

-- Создание таблицы credit_payments
CREATE TABLE credit_payments (
                                 id BIGINT PRIMARY KEY,
                                 number VARCHAR(50) NOT NULL,
                                 type VARCHAR(20) NOT NULL,
                                 exp_date TIMESTAMP NOT NULL,
                                 CONSTRAINT fk_credit_payment FOREIGN KEY (id) REFERENCES payments(id)
);

-- Создание таблицы users
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(255) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL,
                       role VARCHAR(20) NOT NULL,
                       customer_id BIGINT,
                       CONSTRAINT fk_user_customer FOREIGN KEY (customer_id) REFERENCES customers(id)
);

-- Создание таблицы auth_tokens
CREATE TABLE auth_tokens (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             token VARCHAR(255) NOT NULL UNIQUE,
                             expiry_date TIMESTAMP NOT NULL,
                             user_id BIGINT NOT NULL,
                             CONSTRAINT fk_token_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- rollback drop table customers;